services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www/src:cached
      - ./public:/var/www/public:cached
      - ./composer.json:/var/www/composer.json:ro
      - ./composer.lock:/var/www/composer.lock:ro
      - vendor_data:/var/www/vendor
    env_file: .env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - vendor_data:/var/www/vendor:ro
    depends_on:
      - php

  db:
    image: postgres:16-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:11
    # use command: -X migrate for debugging
    command: migrate
    depends_on:
      - db
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/${PG_DB}
      FLYWAY_USER: ${PG_USER}
      FLYWAY_PASSWORD: ${PG_PASSWORD}
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./db/migration:/flyway/sql:ro
      
volumes:
  pgdata:    
    driver: local
  vendor_data:
    driver: local